# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 852)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.images = QtWidgets.QLabel(self.centralwidget)
        self.images.setGeometry(QtCore.QRect(10, 10, 891, 591))
        self.images.setAlignment(QtCore.Qt.AlignCenter)
        self.images.setObjectName("images")
        self.result = QtWidgets.QTextEdit(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(110, 610, 621, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result.setFont(font)
        self.result.setReadOnly(True)
        self.result.setObjectName("result")
        self.input_bt = QtWidgets.QPushButton(self.centralwidget)
        self.input_bt.setGeometry(QtCore.QRect(10, 610, 91, 41))
        self.input_bt.setObjectName("input_bt")
        self.textselected = QtWidgets.QLineEdit(self.centralwidget)
        self.textselected.setGeometry(QtCore.QRect(740, 610, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textselected.setFont(font)
        self.textselected.setObjectName("textselected")
        self.ocr_bt = QtWidgets.QPushButton(self.centralwidget)
        self.ocr_bt.setGeometry(QtCore.QRect(740, 700, 91, 41))
        self.ocr_bt.setObjectName("ocr_bt")
        self.confirm_bt = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_bt.setGeometry(QtCore.QRect(740, 650, 91, 41))
        self.confirm_bt.setObjectName("confirm_bt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.images.setText(_translate("MainWindow", "Images"))
        self.input_bt.setText(_translate("MainWindow", "Select input"))
        self.ocr_bt.setText(_translate("MainWindow", "OCR"))
        self.confirm_bt.setText(_translate("MainWindow", "Confirm"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
